### ISSUE TITLE
More "Atom-like" Explosions -- Help Needed

### ISSUE THREAD

**Issue by hoovercj** [hoovercj/vscode-power-mode#10]
**Question:**

via https://github.com/Microsoft/vscode/issues/852#issuecomment-311708869
> Can't we have exactly the same experience as we're used to in Atom, without the damn 🎆 . 😞

![atom](https://camo.githubusercontent.com/49b4222b69e7ebdb33376d61bcb3a4e5c39acd1f/68747470733a2f2f692e6769746875622d63616d6f2e636f6d2f623164303362396237613964376463396133326431656162333037623533373866386335396137622f363837343734373037333361326632663633366336663735363432653637363937343638373536323735373336353732363336663665373436353665373432653633366636643266363137333733363537343733326633363338333833343331333532663331333133363331333533353336333532663331333036363331333633343335333632643339363333363335326433313331363533353264333836313636333432643332333633353636333033313636363333383333363133303265363736393636)

![Combo Counter](https://camo.githubusercontent.com/03a3a2acebf176349b9f6021809ea265cc02f0e7/68747470733a2f2f692e6769746875622d63616d6f2e636f6d2f636135373265323265363461343263343466353965316562623430643461316531623734383736312f36383734373437303733336132663266363336633666373536343265363736393734363837353632373537333635373236333666366537343635366537343265363336663664326636313733373336353734373332663331333033353339333033373339333932663331333833383331333733323333333732663338333733363633333236343338333432643338333333323331326433313331363533363264333833333332333432643636333133353334333033363330333436333330363236343265363736393636)
**Answer:**

Not exactly. The Atom extension creates a canvas that it writes particle animations to. VS Code doesn't expose DOM access so I can't do that.

What I _can_ do is replace the "firework" explosions with "particle" explosions if somebody has an appropriate gif with transparent background.

I didn't find any that looked good, so I went with the best I could find.

If you find explosions you'd like to use instead of these ones,  you can do that using this setting:

```
"powermode.customExplosions": [ "<explosion url>",  "<explosion url>",  "<explosion url>" ]
```

The **combo counter** is a similar story. I made some attempts to absolutely position some decorations on the screen but was unsuccessful. They would appear and disappear as you scrolled the first or last line off the screen. I may revisit this in the future.

**Comment by darkvertex** [comment]
The other thing that Atom is doing is changing the particle colours based on what kind of thing you're typing. Notice how in the gif the "hello world" string which is rendered green produces green particles, whereas spaces in the exterior are plain white particles.

If you had an appropriate gif in white, what are the chances you could *tint* it? Would that be crazy?

**Comment by darkvertex** [comment]
Mentioned in issue #1 but posting my first effort here:

![squarepoof1_demo](https://user-images.githubusercontent.com/941331/30360637-9e83bb12-9820-11e7-91a4-755b3d4adf6f.gif)
```
    // ATOM (larger)
    "powermode.customExplosions": [
        "https://i.imgur.com/PB34u4G.gif"
    ],
    "powermode.explosionDuration": 400,
    "powermode.explosionSize": 10,
    "powermode.customCss": {
        "left": "-25px",
        "top": "-30px",
        "z-index": 1
    },
```
```
    // ATOM (small)
    "powermode.customExplosions": [
        "https://i.imgur.com/PB34u4G.gif"
    ],
    "powermode.explosionDuration": 400,
    "powermode.customCss": {
        "left": "-15px",
        "top": "-20px",
        "z-index": 1
    },
```
## *Original GIF*:
![squarepoof1](https://user-images.githubusercontent.com/941331/30360638-9e842386-9820-11e7-9c12-948e2c1bc40e.gif)
(it's white on white in github so you may not see it, but it's there!)

**Comment by hoovercj** [comment]
Thanks for these, they are great! I'll take a closer look at the other gifs soon, but for now I'm focusing on this one and seeing if there is a way to tint it.

I spent time yesterday messing around and didn't have any luck, but I'm confident that something will work. Here's what I found:

**Getting the color:**

* Javascript - There's no way to get the current color in JavaScript. Even if I could get the current token type (i.e. comment), I can't translate that to the theme color. That rules out a few methods.
* CSS - the `currentColor` keyword is quite helpful. I have shown that I can set the background color of the explosions to be the same color as the text. The version of chrome used in vscode doesn't support `color-mod`, so I can't modify this color in any way.

**Changing the image color**:

* Filter - filter seemed promising, I could use the `hue shift` to change the white to any color. Unfortunately it only operates on degrees and as I cannot get the color in JavaScript I can't calculate the number of degrees needed. This is out
* Blend modes - I can set the background color to be the color of the text and blend the white gif with it, but then the background color is visible, so that doesn't work. Maybe I'm missing something here
* clip/mask - if the gif is an animated clip path or masking SVG, I should be able to set the background color to the current color but have only the areas needed to show the particles be transparent. This seems promising but I couldn't make it work last night but I can't remember why. I'll revisit this again because I think it is the most likely to work
* Parameterized animated SVG - I tried using an SVG embedded in a url() the with fill set to currentColor but that didn't work. Maybe there is a way to do it by using a file reference to the svg and passing a parameter to it

Here is an example of a simple animated SVG:

```
<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <style type="text/css">
        #a { animation: x .5s ease alternate infinite; }

        @keyframes x {
           from { x: 0; }
             to { x: 80; }
        }
    </style>
    // Note: currentColor doesn't work here, it doesn't get the currentColor from the document scope
    <rect id="a" x="0" y="0" width="20" height="20" fill="pink" />
</svg>
```

**Comment by hoovercj** [comment]
**Update:**

I've had some success using the gif as the mask, but I need to figure out how to properly size and position it. `-webkit-mask-image: url('https://i.imgur.com/PB34u4G.gif')`

I'll pick that up tonight.

**Comment by darkvertex** [comment]
Great progress! Looking forward to the tinting feature.

**Comment by hoovercj** [comment]
This is what it looks like with the current gifs (actually pretty cool if you ask me):

![demo-atom-like-v1-2](https://user-images.githubusercontent.com/2957173/30457473-b930b4b4-99a7-11e7-8d4b-029354c06efc.gif)

And this is what it roughly looks like with the particle gif (much closer to the original look):
**Note:** I set the duration to 500.

![demo-atom-like-v1](https://user-images.githubusercontent.com/2957173/30457158-a17eb2d6-99a6-11e7-8afd-1fec55ec0a8a.gif)

Now compare with atom:

![atom](https://camo.githubusercontent.com/49b4222b69e7ebdb33376d61bcb3a4e5c39acd1f/68747470733a2f2f692e6769746875622d63616d6f2e636f6d2f623164303362396237613964376463396133326431656162333037623533373866386335396137622f363837343734373037333361326632663633366336663735363432653637363937343638373536323735373336353732363336663665373436353665373432653633366636643266363137333733363537343733326633363338333833343331333532663331333133363331333533353336333532663331333036363331333633343335333632643339363333363335326433313331363533353264333836313636333432643332333633353636333033313636363333383333363133303265363736393636)

We're definitely getting close! I'm thrilled.

So what's next? Well, polishing my code for one. But regarding the gifs, I think you're right that it would look best if there were some different gifs of the particle effects to cycle through. If you are interested in doing that, then I'll go through and tweak the settings to find the best default experience.

**Comment by darkvertex** [comment]
Haha, awesome! The coloured fireworks are actually much nicer than I thought they would be.

I'm down to provide a some more variations of that style of square particles, maybe one series like this one and one that's a bit more intense. It'll be much better than repeating the same one over and over, that's for sure.

Something I was also wondering... Atom's particles have quite a wide area. If I gave you a similar thing that was much larger, do you think it would drastically impair the plugin performance? In your opinion for the sake of this plugin, is it worse to have a large file size or a large resolution?

I was debating with myself whether to oblige in a much larger gif just to make that more realistic but settled on the smaller one shown earlier, but if you tell me as long as it's still a few KB it's ok to have a much wider one, I think I can get a lot closer to Atom's style.

Another thing is Atom's particles fade out with age, which my initial version did not. I will try a version where they do (though with gif dithering I don't expect it to look as clean, but hopefully still cool looking.)

I'll try to provide you some new gifs in the next few days.

**Comment by hoovercj** [comment]
You can try to fade them out, but don't worry too much. To make that effect carry over into this, I would have to play around with a blend mode and stuff and I'm not sure it will work.

I have another idea for fading them out using multiple decorations with an opacity animation property. But I consider that a feature for vNext.

Regarding size, you can just change the explosion size in the settings and see if that affects the performance or visual quality. If it still renders fine when it is really tall, it should render fine when it is  wide, too. If it runs fine then I can make it wider/add a separate setting for width. But I really don't know the answer, I'm also mostly playing things by eye, throwing things at the screen and seeing what sticks.

No rush on the gifs, the extension has survived this long without them so it will be fine.

**Comment by darkvertex** [comment]
If I was to give you a gif of a single particle, would you be able to fade it yourself? could instance a few (say ~5) from a randomized set of gifs of single particle gifs to make the effect even more similar to Atom's, maybe.

**Comment by hoovercj** [comment]
I haven't looked at the performance implications of stacking multiple background images/or seeing if i can use multiple images as masks. I can try that out later and see what happens.

**Comment by horvay** [comment]
Hey @hoovercj, any chance you can release what you have so far? I think it's super cool already.

**Comment by hoovercj** [comment]
Ok, I can use multiple images at once and the performance seems ok.

But I don't think I really understand your comment, are you talking about two different things?

1) Fading them: Can I do it? I tried to animate the opacity and couldn't make it work, so i'll consider fading out to be a future priority

2) Instead of making ~3 gifs that have multiple particles but in a different pattern, would it be possible for me to composite them myself by combining multiple gifs with only a single particle?: No. It might be possible but it adds much more complexity than I'd like. It could be pursued in the future, but I think the jump from where we are today, to having just a couple particle effects is a big enough step forward.

**Comment by hoovercj** [comment]
@horvay I was planning on waiting a week to see if @darkvertex gave me any more assets. If I don't get anything by this weekend I'll consider publishing what I have and updating it later when new assets arrive.

**Comment by darkvertex** [comment]
@hoovercj Don't release yet, I wanna give you some more stuff. :)

As for your questions:

> Fading them: Can I do it? I tried to animate the opacity and couldn't make it work, so i'll consider fading out to be a future priority

No worries. I'll try with a bit of transparency dithering; it's just not as pretty as Atom's smooth fade out. I'll also try a version where I just shrink them to nothingness as they die.


> Instead of making ~3 gifs that have multiple particles but in a different pattern, would it be possible for me to composite them myself by combining multiple gifs with only a single particle?: No. It might be possible but it adds much more complexity than I'd like.

Ok, I'll do a few variations similar to what I first gave you first and you can just have it randomly pick from the list.

**Comment by hoovercj** [comment]
What is transparency dithering? Is that just essentially removing pixels from them so there are less and less pixels that are opaque to make it look like it is fading?

Thanks again for helping out!

**Comment by darkvertex** [comment]
Yes, that's how GIFs can fake transparency without really doing it. The format's transparency feature is either on or off for a given pixel, it can't be a float like with PNG... so many GIF encoders have some kind of optional dithering algorithm that can be enabled to kind of fake the illusion of a transparency gradient.

That's how my flame gif works. If you were to extract one frame or pause the gif somehow, you'd see the edges are kinda rough, but it's the best this beloved format from the 90s can give you. :)

![dithering example](http://paulbourke.net/dataformats/bitmaps/colourconfig2.gif)
Found this example here: http://paulbourke.net/dataformats/bitmaps/
This is zoomed in greatly, but it shows you what "pattern dithering" does. First left is a real gradient, the rest is dithering with different patterns. (Zoom out / shrink this enough and it _kinda_ looks like it's fading in a gradient though!)

**Comment by hoovercj** [comment]
TIL :-) Thanks for the primer!

**Comment by darkvertex** [comment]
Check these out:

**Series 2 - with dithered fadeout**
```
    // ATOM style - #2 with dithered fadeout
    "powermode.customExplosions": [
        "https://i.imgur.com/gqMKIfF.gif", // a
        "https://i.imgur.com/7mNcSCt.gif", // b
        "https://i.imgur.com/Ue6CPiX.gif", // c
        "https://i.imgur.com/Q9ILKnX.gif", // d
        "https://i.imgur.com/e1VvgRR.gif", // e
        "https://i.imgur.com/4XosXhe.gif", // f
        "https://i.imgur.com/kEVf1bt.gif", // g
        "https://i.imgur.com/hAEOO7n.gif", // h
        "https://i.imgur.com/nihfLzN.gif", // i
        "https://i.imgur.com/MoaAKh6.gif"  // j
    ],
    "powermode.explosionDuration": 400,
    "powermode.explosionSize": 20,
    "powermode.customCss": {
        "left": "-75px",
        "top": "-75px",
        "z-index": 1
    },
```

**Series 2 - with dithered fadeout and shrink-out**
```
    // ATOM style - #2 with dithered fadeout and shrink-out
    "powermode.customExplosions": [
        "https://i.imgur.com/mdQ0TKQ.gif", // a
        "https://i.imgur.com/hkF1KRD.gif", // b
        "https://i.imgur.com/b13xe6S.gif", // c
        "https://i.imgur.com/9ySfFkw.gif", // d
        "https://i.imgur.com/YBWPDwq.gif", // e
        "https://i.imgur.com/wGvcNek.gif", // f
        "https://i.imgur.com/d47rbZa.gif", // g
        "https://i.imgur.com/QI0NzlL.gif", // h
        "https://i.imgur.com/UFMxbpm.gif", // i
        "https://i.imgur.com/OrLKEGG.gif"  // j
    ],
    "powermode.explosionDuration": 400,
    "powermode.explosionSize": 20,
    "powermode.customCss": {
        "left": "-75px",
        "top": "-75px",
        "z-index": 1
    },
```

**Series 2 - shrink-out only:**
```
    // ATOM style - #2 with shrink only, no fadeout
    "powermode.customExplosions": [
        "https://i.imgur.com/MiQWTj5.gif", // a
        "https://i.imgur.com/3GKCOch.gif", // b
        "https://i.imgur.com/K8e0aqM.gif", // c
        "https://i.imgur.com/4RXiBAx.gif", // d
        "https://i.imgur.com/BvpfEgA.gif", // e
        "https://i.imgur.com/DaOTgug.gif", // f
        "https://i.imgur.com/Tuv8EsP.gif", // g
        "https://i.imgur.com/eM5CSno.gif", // h
        "https://i.imgur.com/2lsLIEY.gif", // i
        "https://i.imgur.com/dnxBYmA.gif"  // j
    ],
    "powermode.explosionDuration": 400,
    "powermode.explosionSize": 20,
    "powermode.customCss": {
        "left": "-75px",
        "top": "-75px",
        "z-index": 1
    },
```

I did 10 similar but different motion variations. Each gif is 300x300, 10 frames at 40ms per frame, so the duration of 400ms should do the trick.

My favourite so far is the "shrink-out only" one. What about you?

ps: No "demo gifs" this time because I just wrote out 30 little GIFs by hand and my fingers need a rest. :P

**Comment by hoovercj** [comment]
Huge thanks, @darkvertex! And @horvay -- I've published an update

**Comment by darkvertex** [comment]
Can I ask which of my variations made it into the release? (unless you added them all? lol)

**Comment by TransparentLC** [comment]
@hoovercj The GIF solution is great but not perfect! The particles in Atom are transparent. GIF can't do that and the frame rate is limited.

I tried animated SVG and it works.

![](https://i.imgur.com/dueyPZe.gif)

```json
{
    "powermode.enabled": true,
    "powermode.comboTimeout": 3,
    "powermode.customExplosions": [
        "https://files.catbox.moe/li68ef.svg",
        "https://files.catbox.moe/hslpu3.svg",
        "https://files.catbox.moe/0a1u03.svg",
        "https://files.catbox.moe/5minku.svg",
        "https://files.catbox.moe/w963mc.svg",
        "https://files.catbox.moe/8obqwu.svg",
        "https://files.catbox.moe/ewj8ww.svg",
        "https://files.catbox.moe/890efp.svg",
        "https://files.catbox.moe/axuing.svg",
        "https://files.catbox.moe/hmtbdl.svg"
    ],
    "powermode.gifMode": "restart",
    "powermode.maxExplosions": 100,
    "powermode.explosionFrequency": 1,
    "powermode.explosionOrder": "random",
    "powermode.explosionDuration": 2000,
    "powermode.explosionSize": 24
}
```

It would be better if the SVGs are converted to data URIs...

The movement of particle is random so I made a PowerShell function [(Source code)](https://pastebin.com/y6iQq0VQ) to generate the animated SVGs. The number and size of the particle and the duration of animation can be customize :)

Usage:

```powershell
Get-AnimatedParticleSVG -Count 10 -Size 5 -Duration 1 | Out-File 'particles.svg' -NoNewLine
```

**Comment by hudannag** [comment]
Here is mine:

`"powermode.enabled": true,
    "powermode.explosionDuration": 500,
    "powermode.maxExplosions": 10,
    "powermode.comboTimeout": 3,
    "powermode.shakeIntensity": 2,
    "powermode.explosionFrequency": 3,
    "powermode.explosionSize": 120,
    "powermode.customCss": {
        "margin-left": "-200px",
        "margin-top": "500px",
        "position": "fixed"
    },
    "powermode.customExplosions":
        ["https://i.imgur.com/BfxzAts.png",
        "https://i.imgur.com/dVQjcqc.png",
        "https://i.imgur.com/sUMSgII.png",
        "https://i.imgur.com/V81tYq1.png",
        "https://i.imgur.com/C6ey7KC.png",
        "https://i.imgur.com/4SabKqW.png",
        "https://i.imgur.com/Lqs0JcF.png",
        "https://i.imgur.com/taSGO7d.png",
        "https://i.imgur.com/n8Z5a3w.png",
        "https://i.imgur.com/ajxqJFZ.png",
        "https://i.imgur.com/2t7TL4q.png",
        "https://i.imgur.com/taSGO7d.png",
        "https://i.imgur.com/FOKwl6H.png",
        "https://i.imgur.com/falaNVU.png"],`
