### ISSUE TITLE
Effects not working

### ISSUE THREAD

**Issue by ShohorabHShawon** [hoovercj/vscode-power-mode#108]
Only the shake effect is working correctly. Effects are not working. How can I solve it?

**Comment by ShohorabHShawon** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/68371168/233376124-9e4b82f9-ef39-450d-9b8a-bda273f8a399.png)

**Comment by ShohorabHShawon** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/68371168/233376844-b14a43cb-c72e-407b-b15f-a024b64bfd0f.png)
![Screenshot_1](https://user-images.githubusercontent.com/68371168/233376849-5963744a-1614-4daf-b66e-216fcd6bbd24.png)

**Comment by BakiAbdullah** [comment]
Just Downgrade your version to v2.2.0
