### ISSUE TITLE
Particle Customisation: No Shake

### ISSUE THREAD

**Issue by micnguyen** [hoovercj/vscode-power-mode#15]
Love the plugin and the particule preset but I am heavily lactose intolerant and unfortunately can't have too much (milk)shake. It would be good if we could customise the particle shake factor (0 to MAXIMUM SHAKE).

**Comment by micnguyen** [comment]
My body, I am an idiot and didn't realise there were more settings outside of the README. Nevermind! :)

**Comment by benmanu** [comment]
In case someone else runs into this, it's the `powermode. enableShake` (boolean) and `powermode. shakeIntensity` (number) settings 😄
