### ISSUE TITLE
Disable shake? Not documented.

### ISSUE THREAD

**Issue by ath88** [hoovercj/vscode-power-mode#19]
~~I would love to just have the Atom-like particle explosions, not the shake.~~

~~Would exposing this option as setting be prudent?~~

This option is available as `powermode.enableShake`, but it's just not documented. It should be, I guess?

**Comment by hoovercj** [comment]
You're right, this is an important setting so I have added this to the README.

For anybody else wondering about all of the settings available, you can see them by going to `settings.json` and typing `"powermode.` and scrolling through the intellisense or by going [here](https://github.com/hoovercj/vscode-power-mode/blob/master/package.json) and reading the configuration option. There are just too many settings to explain them all in the README.

**Comment by alexluong** [comment]
Hey, I was looking for this when I came across this issue This is how I learn `powermode.enableShake` exists. I don't think it's in the README yet. I just wanna let you know, @hoovercj. Thanks a lot for this awesome extension.
