### ISSUE TITLE
The particles is always is always at the beginning of the line

### ISSUE THREAD

**Issue by HyetPang** [hoovercj/vscode-power-mode#22]
when i installled the plugin im my vcs Code, The particles is always is always at the beginning of the line.
Here are some information and configuration:
* system: win7
* vsc version: 1.91.1
* configuration
    "powermode.enabled": true,
    "powermode.presets":"particles",
    "powermode.backgroundMode": "mask",
    "powermode.enableShake": true,
    "powermode.explosionDuration": 360,

**Comment by hoovercj** [comment]
Thanks for reporting this! I'm tracking the issue at #20 and hope to find a fix after the holidays/new year.

**Comment by hoovercj** [comment]
A fix has just been published in version 2.1.0.
