### ISSUE TITLE
Explosions only happens at the beginning of the line

### ISSUE THREAD

**Issue by lisnb** [hoovercj/vscode-power-mode#23]
Great extention~ 

I have a problem, with
Power Mode 2.0
VSCode 1.19.2

the explosions only explodes at the beginning of the line, though the cursor moves normally
I try to uninstall this extension for a couple of times and restart vscode a couple of times and enable , disable this entension a couple of times, but it still didn't work

+_+

**Comment by kirkone** [comment]
I have the same issue and did some test to get around this but had no luck.

I will dig in to this a little more next weekend. Maybe I can find a solution.

**Comment by hoovercj** [comment]
Thanks to @kirkone for submitting a fix for this. It is published in version 2.1.0
