### ISSUE TITLE
Is there any way I can hide the tips in the status bar, thanks

### ISSUE THREAD

**Issue by Xiongqi-XQ** [hoovercj/vscode-power-mode#26]
![tim 20180119101724](https://user-images.githubusercontent.com/25862498/35131603-03ddf3b0-fd02-11e7-88fc-e6187ff8439b.png)

**Comment by argordmel** [comment]
I've the same question, it's possible?

**Comment by Xiongqi-XQ** [comment]
still can't

**Comment by hoovercj** [comment]
Great suggestion. There are now two new settings to disable the combo meter and the timer added in version `2.2.0`.

```
powermode.enableStatusBarComboCounter: false,
powermode.enableStatusBarComboTimer: false
```
