### ISSUE TITLE
reset shake sooner

### ISSUE THREAD

**Issue by horvay** [hoovercj/vscode-power-mode#3]
I noticed that when the screen "shakes," it resets the position of text after the powermode combo has ended.

Would it be possible to reset the position of the text after shaking almost immediately?

![shake_example](https://user-images.githubusercontent.com/7866855/28140636-1d2b950a-6727-11e7-91f6-e0517459692f.gif)

**Comment by horvay** [comment]
For now, I'm just putting the shake to a much lesser number as you suggested in the review section

**Comment by horvay** [comment]
So I forked and made the change. But then I decided to take a stab at the explosions too..

Here is the final result:
![new_explosions](https://user-images.githubusercontent.com/7866855/28196929-96f9d5ea-6821-11e7-8f95-c0011ae10403.gif)

Basically I render whitespace right above the line you are typing on, and then use position: absolute on the whitespace decorator to put it where the cursor is. You can see the whitespace being created above the line you are typing on.

I try to clean up the whitespace, but it's not easy, but I think I get most of it.  

So I turned on: "files.trimTrailingWhitespace": true, which removes all the whitespace when saving. 
Also I have autosave on: "files.autoSave": "afterDelay".

It uses the cursor position (line/character) to find where to put the explosion, but CodeLense really ruins it. 

Do you know a way to detect how many codeLenses are visible? If so, then I could take that into account in the math.

Anyways, what do you think? Should I create a pull request, or maybe just release it separately since it has limitations?

I could at least do a pull request for the shake issue...

**Comment by horvay** [comment]
I figured out the CodeLenses issue

**Comment by hoovercj** [comment]
Hi horvay, for some reason I'm not receiving notifications for this issue, I wish I could have replied sooner.

I'd love a PR to reset the screen shake.

I'd also love to integrate the "floating" explosions, perhaps behind a separate config flag, something like:
```
"powermode.explosionType": {
    "type": "string",
    "default": "default",
    "enum": [
        "default",
        "experimental"
    ],
    "description": "Set to 'experimental' to use experimental explosions. May be unstable, see README for more info."
},
```

If you'd like to do a couple PR's for those that would be great, otherwise I can look at doing the integration myself later (it's still sleep time in my timezone).

I'm excited to look into your code and see what you've done

**Comment by hoovercj** [comment]
Meh, I couldn't sleep and some of your ideas inspired me to take another swing at this.

I just published version 1.0 which includes the shake reset (obvious idea, thanks for sharing!) and improved explosions without having to deal with whitespace or edits.

![image](https://github.com/hoovercj/vscode-power-mode/blob/7b00dab2fe01ed7eed8fc4ba8536141d314680b8/images/demo.gif?raw=true)

I'll close this issue, please open more if you find more issues!

**Comment by horvay** [comment]
Ok, this is amazing. I almost feel dumb for not thinking of this implementation. Well done!

**Comment by hoovercj** [comment]
@horvay imagine how silly I feel for not thinking of it the first time around ;-)
