### ISSUE TITLE
[Bug] Setting combo timer to a float or negative value allows for infinite combo timeout

### ISSUE THREAD

**Issue by lachieh** [hoovercj/vscode-power-mode#33]
Setting this:
`"powermode.comboTimeout": 1.5,`

or this: 
`"powermode.comboTimeout": -2,`

Leads to this:
![screenshot_107](https://user-images.githubusercontent.com/1687902/36817202-4c3effe8-1cae-11e8-9234-20f30eb94953.jpg)

:boom: INFINITE COMBO :boom:

I'd suggest changing to a string and setting it to accept values as seconds or milliseconds either `1.5s` or `1500ms`. This is similar to how times in CSS work.

**Comment by hoovercj** [comment]
This should be fixed in the newly published version 2.2.0
