### ISSUE TITLE
Do not support VS2017

### ISSUE THREAD

**Issue by XiaoBingtong** [hoovercj/vscode-power-mode#35]
Can you upgrade it?

**Comment by hoovercj** [comment]
This extension is for `https://code.visualstudio.com`.

These two extensions support Visual Studio 2017.

[LiamMorrow's Power Mode](https://marketplace.visualstudio.com/items?itemName=LiamMorrow.PowerMode)
[BigEgg's Power Mode](https://marketplace.visualstudio.com/items?itemName=BigEgg.PowerMode)
