### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by JhonnyJason** [hoovercj/vscode-power-mode#36]
Awesome plugin, 

I just face the problem that I have no Idea to configure it properly xD 

I mean I can use and adjust the parameters of those settings which are available from the beginning and I can read some settings available in the Readme here - thus being capable to also adjust them.

But for example "powermode.presets" appears to have something to do with the possibility to activate this "Rift" which appear to be are those nice futuristic plasma explotions.
 
Still I have no Idea if I have to configure:
`"powermode.presets": true`
or 
"powermode.presets": "Rift"
or 
`"powermode.presets": NameOfSomeValidPreset`
or
`"powermode.presets": NameOfSomeValidConfigurationForPresets`
or 
`whatever^^... `

I mean it is sort of my problem to that I'm probabl too hesitant to start with breadth-first-search of everything I could think of as possibility.

On the other hand when I bruteforce this problem from my side I probably waste severly more time then when somebody who understands how the configuration works and which possibilities are there - could write it down in the Github readme.

I also guess that other people might also face the problem that they don't immediatly understand the possbilities of configurations and don't have the "correct" instinct on what to try first.

Would be super awesome :D 
Cheers!

**Comment by hoovercj** [comment]
In the `settings.json` file there should be autocompletion/intellisense for the configuration options. So when you type `"powermode.presets": ` you should get a list of the presets available. If they don't appear, I believe `ctrl+space` activates intellisense. Please let me know if that doesn't work!

**Comment by JhonnyJason** [comment]
Works perfectly, thanks!

Guess I don't trust intellisense enough to have come up with that idea ^-^'
