### ISSUE TITLE
VSCODE Bug Report 'setDecorations'

### ISSUE THREAD

**Issue by jgrunwald** [hoovercj/vscode-power-mode#42]
- Extension Name: vscode-power-mode
- Extension Version: 2.2.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 32,
		"activateCallTime": 3,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'setDecorations' of undefined"
		}
	]
}
```

**Comment by hoovercj** [comment]
Thanks for reporting this! I believe I fixed anything that could have caused this in the just-shipped v3.0
