### ISSUE TITLE
Explosions happen after typing stopped

### ISSUE THREAD

**Issue by Narigo** [hoovercj/vscode-power-mode#46]
As you can see in the screencast, I've stopped typing and after being done, there is an extra explosion. This is particular annoying, when shaking is turned on. Is it possible to not start any pending(?) explosions when no more typing occurs?

![screencast](https://user-images.githubusercontent.com/1767865/51580565-4403c880-1ec5-11e9-909e-6bfccbe6c667.gif)

**Comment by hyprhare** [comment]
**Would you be willing to post a list of your Powermode settings, from your vscode Settings.json file?**
_Doing so will provide a great deal of insight into how we can replicate this behavior._

I've witnessed something like this occur when the "Explosion Duration" setting is changed away from `1000` ms. 

It's actually quite odd... notice the behavior observed below: (eg.)
> gifs-time-to-play = 400ms, Explosion Duration = 1000ms, observed-behavior => plays .gif **once**.
> gifs-time-to-play = 400ms, Explosion Duration = 999ms, observed-behavior => plays .gif ~**thrice**.
> gifs-time-to-play = 400ms, Explosion Duration = 1001ms, observed-behavior => plays .gif ~**thrice**.
> gifs-time-to-play = 400ms, Explosion Duration = 400ms, observed-behavior => plays .gif once.
> gifs-time-to-play = 400ms, Explosion Duration = 200ms, observed-behavior => plays .gif half-way.
