### ISSUE TITLE
Center combo timer spinning icon in the status bar

### ISSUE THREAD

**Issue by charlesferreira** [hoovercj/vscode-power-mode#54]
The icon flicks back into position after finishing a turn.

![Peek 2019-08-20 10-10](https://user-images.githubusercontent.com/11216339/63349949-d91f5080-c332-11e9-9721-b0ff777c350f.gif)

**Comment by hoovercj** [comment]
I can't repro this so VS Code must have fixed it, but thanks for reporting!
