### ISSUE TITLE
Explosion appears at the beginning of the line when hitting backspace.

### ISSUE THREAD

**Issue by ayrtonmassey** [hoovercj/vscode-power-mode#6]
When I hit backspace, sometimes the explosion appears at the start of the line instead of at my current cursor position:

![screenshot of bug](http://i.imgur.com/pqKs6em.png)

Repro steps:
1. Write text until power-mode activates.
2. Hit backspace until an explosion appears.

**Comment by hoovercj** [comment]
This is known and already documented in the readme. I believe it is caused by the letter element being deleted and the after pseudoelement losing its anchor and positioning to the beginning before it is itself disposed.

If you think it might be something else please reopen.

**Comment by hoovercj** [comment]
I believe this behavior has been fixed in the latest 2.1.0 update.
