### ISSUE TITLE
A way to disable shaking?

### ISSUE THREAD

**Issue by kud** [hoovercj/vscode-power-mode#64]
Is there a way to disable the shaking?

Thank you :)

**Comment by hoovercj** [comment]
@kud yes there is, in the user settings you can uncheck the "enableShake" setting to disable shaking. I hope that helps!

![image](https://user-images.githubusercontent.com/2957173/84252640-244b5f80-ab0f-11ea-91e7-74e5ade930bb.png)

**Comment by kud** [comment]
Thank you!

I'm a beginning with VS Code, and I mostly use the json way. Thanks!

**Comment by kud** [comment]
Perfect! It works! Thanks again!
