### ISSUE TITLE
Shortcut to enable/disable powermode

### ISSUE THREAD

**Issue by GregorBiswanger** [hoovercj/vscode-power-mode#65]
First of all.. a big thank you for your amazing extension...

I would like to be able to use a shortcut to turn power mode on and off please..

**Comment by hoovercj** [comment]
You can set up keyboard shortcuts to change any vscode setting using this
extension:

https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler

I hope that helps!

**Comment by GregorBiswanger** [comment]
Yes, that helps me.. thanks :)
