### ISSUE TITLE
ComboCounter not working as intended

### ISSUE THREAD

**Issue by ulquiomaru** [hoovercj/vscode-power-mode#68]
Setting `"powermode.enableStatusBarComboTimer": false` disposes the ComboTimer functionality completely.

The functionality should be separated from the presentation layer, ie. the status bar view.

**Comment by hoovercj** [comment]
Thanks @ulquiomaru for pointing this out and offering a solution! I've just shipped 3.0 which included a big refactoring and adds new control over whether and even where to show the combo and timer. It should fix this issue!

I've redone all the settings so they should be much easier to find, understand, and update in the settings UI. I hope this helps!
