### ISSUE TITLE
combo timer does not work if not displayed in status bar

### ISSUE THREAD

**Issue by georgejecook** [hoovercj/vscode-power-mode#73]
it's really distracting in the status bar; but if I don't show it; then the timer doesn't work :(

**Comment by mdmahbubhelal** [comment]
I have the same problem.

**Comment by hoovercj** [comment]
Thanks for sharing! I've just shipped 3.0 which fixes this issue and adds new control over whether and even where to show the combo and timer.

I've redone all the settings so they should be much easier to find, understand, and update in the settings UI. I hope this helps!
