### ISSUE TITLE
[Bug found on my end] The shake of the power mode is only horizontal

### ISSUE THREAD

**Issue by oultrox** [hoovercj/vscode-power-mode#8]
# The problem
Hello there hoover! I've already mentioned this in another issue but I'll try to make it official and explicit. 

I don't know why, but the shake is only horizontal and it seems like adding spaces and deleting them in my vscode power mode setting.

## What I tried
- Reinstalled PowerMode
- Reinstalled VsCode as well

None of this worked out.

I'll let you a gif:
![vscodebug](https://user-images.githubusercontent.com/10330846/28831489-aeebc1ec-76a7-11e7-9bf5-b912a481d2b8.gif)
_(Horizontally*)_
Let me know if you need more info!

**Comment by hoovercj** [comment]
It's quite odd, it repros for some people but not others. I think @pedersenthomas also experienced this. Thomas, can we investigate this together?

**Comment by PedersenThomas** [comment]
Of course. Do you have an idea where to start on this?

**Comment by oultrox** [comment]
Any update on this? Just curious if I can help on something, altho I'm not experienced at js.

**Comment by oultrox** [comment]
Heya @hoovercj  maybe it's some kind of configuration i'm not doing properly, because I installed vscode power mode in my home last night and still not working vertically. 

### This is my configuration
![image](https://user-images.githubusercontent.com/10330846/30808282-d2747c92-a1d3-11e7-987b-93990942e4dc.png)

**Comment by MeowLucian** [comment]
I have the same problem.

**Comment by hoovercj** [comment]
Hello @oultrox and @MeowLucian! Thanks for your patience. @PedersenThomas and I finally got a chance to sit down and look at this and I think we found the problem.

For whatever reason, the vertical shake only seems to work when `editor.renderWhitespace` is set to `boundary` or `all`. I have always had that set so I never noticed that it wasn't working when it isn't set.

But fear not, if you don't want to see the whitespace rendered, you can set the whitespace color to be invisible.

```
"editor.renderWhitespace": "all",
"workbench.colorCustomizations": {
    "editorWhitespace.foreground": "#FFFFFF00"
},
```

I have zero clue why this setting would make a difference, but maybe I'll dig deeper into the VS Code source later and see what it does that might impact this. But until then, please let me know if this fixes the issue for you!

**Comment by MeowLucian** [comment]
Thanks, it works now. ^^

**Comment by hoovercj** [comment]
Glad to hear it :-)

**Comment by oultrox** [comment]
It works, thank you!
