### ISSUE TITLE
Offline Support Issue

### ISSUE THREAD

**Issue by DrLonnieJonesPFMP** [hoovercj/vscode-power-mode#80]
I had tried to use a custom explosion offline but it had not loaded correctly. The default explosions had worked as expected.
I have included a few of the methods that I had tried as well as the original file from Giphy.
From the example, it was included as "C:/my/cat/gif"

`    "powermode.customExplosions": [
/*
        "C:\\Python39\\L1.gif",
        "C:\\Python39\\L2.gif",
        "C:\\Python39\\L3.gif"
        
        "../L1.gif",
        "../L2.gif",
        "../L3.gif"
        
        "file:///C:/Users/Lonnie/Pictures/L1.gif",
        "file:///C:/Users/Lonnie/Pictures/L2.gif",
        "file:///C:/Users/Lonnie/Pictures/L3.gif"

        "C:/Users/Lonnie/Pictures/L1.gif",
        "C:/Users/Lonnie/Pictures/L2.gif",
        "C:/Users/Lonnie/Pictures/L3.gif"
*/
        "https://media.giphy.com/media/sLMRyFR4eIEgnFe4mK/giphy.gif",
        "https://media.giphy.com/media/RFvv2miX3KHcOkBwns/giphy.gif",
        "https://media.giphy.com/media/8Hw8ei9OiUXIUlHEBy/giphy.gif"    
    ],
    
    "powermode.explosionOrder": "sequential",
    "powermode.explosionSize": 15,
    "powermode.explosionFrequency": 2,
    "powermode.maxExplosions": 10,
    "powermode.explosionOffset": 0.215,
    "powermode.customCss": {
        "color": "rgba(255, 255, 255, 0.8)",
        "mix-blend-mode": "screen"
    },
    "powermode.gifMode": "restart",
    "powermode.explosionDuration": 1000,
    "powermode.backgroundMode": "mask",
    
    //End of Power Mode Settings

    "editor.codeActionsOnSave": {}
    `

**Comment by hoovercj** [comment]
Thanks for letting me know!

I can see that URLs like https://media.giphy.com/media/sLMRyFR4eIEgnFe4mK/giphy.gif work, but local file paths no longer work due to security changes in the browser engine used by VS Code. I've updated the README locally to reflect that and it will go out with the next release that I'm working on
