### ISSUE TITLE
There is a developer who doesn't respect your code

### ISSUE THREAD

**Issue by mochazi** [hoovercj/vscode-power-mode#82]
On the bilibilibili video website, a blogger forked your version. After only 21 commits and only modifying true and false, he declared that the author of the vscode plug-in was his own, and the plug-in name was OSU mode2

[bilibilibili Video link](https://www.bilibili.com/video/BV1dR4y1n7tW)
[OSU Mode2 vscode-link](https://marketplace.visualstudio.com/items?itemName=lxfriday.vscode-osu2)
[OSU Mode2 github-link](https://github.com/lxfriday/vscode-osu2)

**Comment by hoovercj** [comment]
@mochazi thanks for sharing the information! I think now the other developer has made enough changes and has explicitly thanked me in their work so it is OK.

Also, I have been able to use a few tricks from their version as inspiration and motivation to revive my own branch and release it as v3.0!

So now there is an improved combo meter in Power Mode!

**Comment by ChakraZulu77** [comment]
Im recently starting developer class, is this something I should feel safe installing at this point? im just a Neophyte who just woke up from a deep sleep 💯 ;)
