### ISSUE TITLE
Can you turn of the shake effect?

### ISSUE THREAD

**Issue by johannesstroebele91** [hoovercj/vscode-power-mode#84]

**Comment by AuracleTech** [comment]
I wish we could turn off the shake effect, I like the rift effect but the shake makes coding impossible :(

**Comment by hoovercj** [comment]
@AuracleTech @johannesstroebele91 there is an "enableShake" setting that you can find in the extension configuration. If you uncheck that, or set it to false in the JSON file, it should disable the shaking.

I hope that helps!
