### ISSUE TITLE
"Explosion offset" not working with clippy

### ISSUE THREAD

**Issue by Monstarrrr** [hoovercj/vscode-power-mode#85]
The offset works with every other gif but doesn't seem to work with clippy

**Comment by hoovercj** [comment]
@Monstarrrr "clippy" is defined a bit special to get it positioned where it is. To reposition it vertically, you can use the "powermode.customCss" configuration option.

For example, to position it vertically above your text instead of below it, you can try something like:

```
    "powermode.customCss": {
        "top": "-4em" // Default value is 1em to place it below the text
    }
```
