### ISSUE TITLE
I DO NOT WANT TO USE SHAKE AND COMBO.

### ISSUE THREAD

**Issue by MinwooJJ** [hoovercj/vscode-power-mode#87]
How can I remove those from screen?
There is no option description for this!

**Comment by Cloudkkk** [comment]
I just updated the extension, honestly I think the combo is so cool !
for ur question, I find the config like "Timer Enable"  and "Counter Enable", you can switch "hide" option to remove them 
:）

**Comment by mdadils** [comment]
I too faced this problem after the extension got auto updated and settings got changed by itself.
Now this can be marked close.

**Comment by hoovercj** [comment]
These are the settings you can change, or you can modify the json directly:

This will disable the shake:
```json
"powermode.shake.enabled": false,
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/2957173/156117620-9d400cde-b5a5-480d-9fce-33f79a5a9f50.png">

This will hide the new combo meter and timer:
```json
"powermode.combo.location": "off"
```

<img width="611" alt="image" src="https://user-images.githubusercontent.com/2957173/156118253-864a8e7a-61e6-437a-b320-3710b543a528.png">


This will hide the new combo meter but keep the timer:
```json
"powermode.combo.counter": "hide"
```

<img width="499" alt="image" src="https://user-images.githubusercontent.com/2957173/156118322-eee66e6c-1af2-475d-8c92-b8a04c8cffa0.png">

**Comment by hoovercj** [comment]
@mdadils the settings were supposed to be migrated automatically when updating.

So if you had `powermode.enableShake: "false"` in your settings, it should have changed automatically to `"powermode.shake.enabled": "false"`.

If you have any more information that could help me understand why it didn't work, I'd be happy to look into it to see if I can prevent it from happening to others as they update.

Are yous ayin
