### ISSUE TITLE
Warning on all settings.json: `$ref 'definitions/length' in {1} can not be resolved'

### ISSUE THREAD

**Issue by roblourens** [hoovercj/vscode-power-mode#9]
_From @roblourens on August 2, 2017 20:17_

All settings.json files show this warning:

![image](https://user-images.githubusercontent.com/323878/28893044-e56af8ea-7784-11e7-923f-b3ca0125f21b.png)

_Copied from original issue: Microsoft/vscode#31932_

When this extension is installed

**Comment by hoovercj** [comment]
Removed uses of `$ref` from `package.json`.
