### ISSUE TITLE
Feature Request: Horizontal Offset

### ISSUE THREAD

**Issue by emericoude** [hoovercj/vscode-power-mode#94]
I'm using this extension to animate a character! I don't really want it to be on top or below the text you're writing, so having to ability to push it to the side would be great!

**Comment by massoudyan1** [comment]
I would like this aswell

**Comment by hxlnt** [comment]
FYI: You can do this by adding a line like this to `settings.json`:

```JSON
    "powermode.explosions.customCss": {
        "margin-left": "20px"
    },
``` 
Swap out the `-left` for `-right`, `-top`, or `-bottom` if you like.
